options:
  port:
    type: int
    default: 8529
    description: |
      ArangoDB web UI port.
  root_password:
    type: string
    default: ""
    description: |
      Administrator password is empty by default (username root). During the
      installation of the charm the user may choose a new password. If this
      action is not carried out, then a new password will be automatically
      generated. When the charm has been installed the user may change the
      admin password. We recommend to select a secure and robust password
      (please avoid passwords such as "root" or an empty string).
  authentication:
    type: boolean
    default: True
    description: |
      Setting this option to false will turn off authentication on the server
      side so all clients can execute any action without authorization and
      privilege checks. The default value is true.
  package_status:
    default: "install"
    type: string
    description: |
      The status of service-affecting packages will be set to this
      value in the dpkg database. Valid values are "install" and "hold".
  install_sources:
    description: |
      List of extra apt sources, per charm-helpers standard
      format (a yaml list of strings encoded as a string). Each source
      may be either a line that can be added directly to
      sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
      Personal Package Archives, or a distribution component to enable.
    type: string
    default: |
      -  'deb https://download.arangodb.com/arangodb32/xUbuntu_16.04/ /'
  install_keys:
    description: |
      List of signing keys for install_sources package sources, per
      charmhelpers standard format (a yaml list of strings encoded as
      a string). The keys should be the full ASCII armoured GPG public
      keys. While GPG key ids are also supported and looked up on a
      keyserver, operators should be aware that this mechanism is
      insecure. Null can be used if a standard package signing key is
      used that will already be installed on the machine, and for ppa
      sources where the package signing key is securely retrieved from
      Launchpad.
    type: string
    default: |-
      - |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v2

        mQINBFVtxt4BEAC4fnctqB2hfUi5SYzqeY3GOxo5Mj5jmqaxxNamO+qbsJpLarAn
        JnA2+TuH+HOdsZeqFHX1dVL0cmxgEq1Lm+vHgHVj/99O/KF/zCktLlk1qh20/3Qf
        +EHJ37GF7DfNcWalEmq5PByxVf8H2octZhUN3k4cyQxUN6RRKlWnAvS6tUG6KQ6w
        WOJdeeQ5S5O3d1y5cHc5Hb/oxSFgk6TDhI1UU/FVH5rt5rfcHbMMKSp9772Hkpc2
        xgdxNoTZmsFuUBn3x1vQfzfAzAQ4imVVVq4tax71WzL3I8tZMdKrBeK6/Cv/Y2ns
        fDhSl+o32GefEoJm9CzuI2ssRjdnIjGZYblouGlinwoN1RMnny2YU3LXSigQSPfk
        hQh8kqPzrfmA/oiIwO/c2ct5e6Ke8jmJ50X5iU40BHkXit75jMHt/N/ZELkCdE1b
        UHfAV2sOoAUiLqPeMLT4zENKOai3ytppgbm9/xetz0rt8Ex+1sI6CkLnzhX1Kz1i
        Mm+ZZeR8mBRjCrlEDJniS4yg3xglDOoW/TmeLGhXSps2ayVqDCAEL1qXlIO20sHn
        lA+Rtq5Zu48a9AVzydlyHS3ytaM7SYI437aIXWQ5riln2VWEVhHGrs7nTUSm+YLQ
        capaoGZ+B3DyiJZ/bRVnX8OHqZ86GbmOxDHGkXlEP36xrubpGnsDPWlxWQARAQAB
        tD1GcmFuayBDZWxsZXIgKEFyYW5nb0RCIERlYmlhbiBSZXBvc2l0b3J5KSA8aW5m
        b0BhcmFuZ29kYi5jb20+iQI9BBMBAgAnAhsDBQkHhM4AAh4BAheABQJYIHmqBQsJ
        CAcDBRUKCQgLBRYCAwEAAAoJEOqT9eVudR6bOzQP/A82udedhV3Ub+IPKXH1yb0t
        4W/H2IC21PCjTfNMqzuY3HwZkfqEm4wfesnwGkX+yWwFkzcqUYpP9X0GylxUEC8S
        f4qvNsiKPVAvy5SqO2uLVu1eH/2WbeqLvdxQYbFBlyoiOTDtGxoEOhv/h+73qUw5
        WQmR35ab3sq0QUA+8KpavZJAnIWzE1mAnTSc+01XiaoV1zayW1yP9Bk1MIFRE7eK
        WFKLnylCFgBkVbG9S1b2Fzau1upjokAGPYSwNkq545Lj7xzjTKS22qlZH8h2RV0S
        yp9loaL+cfd7okUOdz0DPX0vI42g67TThaVm03NpH3N+6jweh4MBr+XpiNKm6zcX
        OoTU/rrC5VG8aZvGpZHmHRasPvnTIwyAxWXu3/JQdHOu8taPoSwBsdxV0rdNVQQ+
        9BjjM4ochcU3aI2rj2UJ9zKjI1tr9tC7KPLNWyHQ3w+05by97Bruv/D3u5QxgQvt
        6B1p+Y8mo6tB8kubrrV7Q+NHiPpkwU6C7Tk8uysAI80VLQABCViSaWmwBNEVS9Iy
        xqnx5qfj6R9DtW1IU6kNUCfMtB6YDJCwjJcXmSx4MvePjiLuVy2TWXWJrwctgXb7
        C2IH9UELNwJd52x8YSHqxdWvtkMSVyjbFZm7XCxqucyQKB8AXIGZkY3vcMdXueva
        GoFDithM0HpZlCeJn8S4iQI+BBMBAgAoBQJVbcbeAhsDBQkHhM4ABgsJCAcDAgYV
        CAIJCgsEFgIDAQIeAQIXgAAKCRDqk/XlbnUemyAbEACtqYAE1MRas+6hityyNuRR
        Cb1nIePHZKaTIqRK9kPJSI87A1/bAjyyn0Ivzrp7dO25SaXKF2IiDWTBxFBZSAAK
        ykAFv/tdhLqH2l40KXXobYn7/X3dlRATCCZX5nzYC/3LV/3c0PrOp+7sqVqwx7on
        LA0crmntZfeqFMLe66zdX3OxW9lTVCPhCPwiAg++1s1MkzvqUsjXqQkRyfBoVmO2
        TxQVf7iMElmUFRsOr4bVf3exsbliR4ceDBlOXar2YPaw7d73xTvZ436hvL81VQN/
        aFtQDaTdo8niHrIRgLIqe4y7UqBUrcbmkwxc6ZxVaWfdiJJUdwAtNKd3Vj9iN5ni
        UvKJjmTdVxFPgZ8O+fbapmORTZ/FAXnVWyb+cNskokJXIeAfEwuO72NwivoNFG21
        O+FKhz7ac2lRjX09kJD8Yun3XMgy/lwprrhDtewk8KMe5KBRuSVS3i2PSecOeJ5C
        xd9h9l8JruAfnwOrEKQwsgYoJyMcIMl74hRPeBLq+Rp/R71bwJwklxVcFuUQt0ty
        wNIQ0RSiuVNVbx4DeYCe/pavfqluDZr/jJmlLy71KKfwG2dqI/EMZHvl7WOPstcG
        IR+VEwx5PfLbZir4KX+jzLMLUJTy96caAftwnV80Hn2u2l6NNQqfowlNqJxN4u0h
        PlpPG09DjH8B5PY12A7eK7kCDQRVbcbeARAAnOE/JDLP1wF1cKJ5PJWezrRCITAC
        EugD+ts9KtWUx9BsQB2IKnwEQud4f5MkdqalhTXKLpMVEhJKMr3pmxOEM/UITUvh
        aY72FpRXrnvePkmxZL2hxXnPzZpvBPLjDePjKMCBOJN4wBrguMq7oYR0Akq0aaL9
        eEiFKBrMdHzzweP0Ck9IqX/HqKc1LT2jL0gwdKRUR8lJQumbu7k9SbAaYTx0kWIW
        ENBqTagiYptbqBqpVvNo6qhLIsAR99uSvjadzTQhnpsl/V4lZbSoLtvbE5dSD6sL
        HtN4nnRQZea/9q12LwQ+GqhzsckaRsa7XkqWjGzAq/L9zsyVMGyyaI7IL414k/xM
        uS3SFL1GM0dqxVrn1c0WLKfpUdLXiawMZ431kUUtqlYwCSTqFsLEX6jtg5N6WMvS
        ZzI+csMozqNjnT/XtGqmlgp867uJag2I/RqIoBMBwuphCI1SXYkP+HZj5AlQQ17k
        O/r2s3BiHrW/2AD+t34IIF+j2BQq/Ojv3LOG2m2T5bQxd+CkrZ8nzNqrTaHaKnZ5
        93vV5KuUjEi8LqP0BVEaguTrJC9z4t9ledWjOhUa3kfvJVktHmkAdnp5mF7R8FBE
        NVoB0cpmJUo9QWkcRF5ftYgfbhU3MNZ9QvLO0kBMQ3PBT0drGMIFfMX7KUpZmyjX
        RasUye66Sy2aOBUAEQEAAYkCJQQYAQIADwUCVW3G3gIbDAUJB4TOAAAKCRDqk/Xl
        bnUem0TGEACHkYVwX049L7B7Y9ptrN2QqxgqwvThWokE/HvBI/zpBvCdsr3T/e6n
        3lVftoRzu2qLf+1bFjjzY4U7FvI6vbEysMBFJOHTBnjOapMzQ8ETyJ16a2USHTq7
        kT6KJATb2HlEPUIhktzMXZI+u4ytGsPTsxPzezeNc4e87g1KmASA3xfC21vWA6GF
        p8yNHVry9IFfxsQRimvbbmPUJhoU7ejuPzcNbhM99eMTDmZLJQjSMSlENw/o3kgs
        ZSyCZleiRy6oZObX0og5HylCobpgQ6zOir1FMGp5YZWoLrktwhmNeBJl8nY4L8nn
        196kJE2gn/21iPzschhMgrUYb94dplcBcxBEDpZXZlR80LY73TkVbONDMcq7tToV
        6xrA4qPLQbNCJXKSK0tpQTTKFD+jyb6olQHC83YIIK/xfcJygw9wCqWph08jf0G3
        Y5Du5R+g2tp/7Z9q4ap9tSIUxjMEbT4bb8rv0ZkfDglvcvZhxe4cYziU9QEdFMtU
        hI8qINaEAqu1NmAl/6KtCl0rYFKEfu5PbN8pvP5+nxskik142OWiTcsX2hOTeIqi
        wye+UAO89hOjHlVerdfwUzQleewCLC2PWnd6QcBJVpHU9K6TDUe+E3n4US9R2bPp
        eY60c0UBI3e1V9jpwGFp4Kel/usbaV+DpV6etF0+tIJsxgEEFTDHOA==
        =7TM0
        -----END PGP PUBLIC KEY BLOCK-----
